/**
 * Tier-0 seed utterances for the embedding-based intent classifier.
 *
 * Four buckets — only `quick_q` triggers a behavioral shortcut in W8.7. The
 * other three are recorded for telemetry and to inform later waves; they all
 * fall through to the existing dual-brain path unchanged.
 *
 * Seeds were drawn from real Telegram chatter patterns + obvious templates,
 * not from any single conversation. Adjust freely; just keep buckets balanced
 * (≈30 each) so cosine distributions stay comparable across routes.
 */

export type Tier0Route = "quick_q" | "tool_call" | "dispatch" | "deep_review"

export const TIER0_SEEDS: Record<Tier0Route, readonly string[]> = {
  quick_q: [
    "good morning",
    "morning",
    "good evening",
    "good night",
    "hey",
    "hello",
    "hi there",
    "what's up",
    "you there",
    "you awake",
    "still alive",
    "ok",
    "okay",
    "yes",
    "yes do it",
    "no",
    "nope",
    "thanks",
    "thank you",
    "got it",
    "sounds good",
    "perfect",
    "nice",
    "cool",
    "awesome",
    "great",
    "what time is it",
    "what's the date",
    "tell me a joke",
    "how are you",
  ],
  tool_call: [
    "show me the network status",
    "check on Frank",
    "is voldemort up",
    "is argus online",
    "ping all nodes",
    "what's the queue look like",
    "show running processes",
    "check disk space on superserver",
    "what's the battery on argus",
    "tail the bridge log",
    "check git status",
    "what files changed today",
    "what's playing on WPFQ",
    "is the radio still streaming",
    "list the radio playlists",
    "show me the calendar",
    "any new emails",
    "what's in my inbox",
    "look at the morning briefing",
    "pull up the schedule",
    "memory usage on voldemort",
    "what's the current PID",
    "any alerts",
    "ssh to scalpel and check uptime",
    "tell me how Frank is doing",
    "what's the load on this box",
    "check on the show builder",
    "list of agents running",
    "show me last week's logs",
    "check Athena for messages",
  ],
  dispatch: [
    "fix the bug in the dispatch parser",
    "refactor the brain module",
    "add a new test for the router",
    "update the README",
    "rename leftHemisphere to leftBrain everywhere",
    "find all places that use the old API",
    "deploy the latest jarvis-prime",
    "build and ship the bridge",
    "write a script to back up the music library",
    "implement Wave 9",
    "add error handling to the responder",
    "make the corpus callosum faster",
    "fix the failing tests",
    "investigate why the bot is slow",
    "look at the bridge code and clean it up",
    "add a feature for X",
    "create a new module for Y",
    "write the SPEC for the next phase",
    "draft the plan",
    "write tests for the classifier",
    "set up the langfuse server",
    "wire up the embedding model",
    "add a new skill manifest",
    "remove the old PHI scanner",
    "extract this into a helper",
    "consolidate these duplicate functions",
    "add logging to track latency",
    "instrument the orchestrator",
    "audit the brain directory",
    "ship a fix for the W8 router",
  ],
  deep_review: [
    "what do you think about this approach",
    "should I use redis or postgres",
    "compare these two architectures",
    "explain the tradeoffs",
    "research the latest in multi-agent systems",
    "what's the best pattern for X",
    "I'm thinking about Y, what do you think",
    "is this safe to deploy on Friday",
    "should we A/B test this first",
    "what would Karpathy say about this",
    "give me your honest opinion",
    "what could go wrong here",
    "find prior art for X",
    "summarize the W9 research",
    "help me think through this design",
    "what's our exposure on X",
    "audit this for security issues",
    "review this PR thoroughly",
    "do a deep review of the brain directory",
    "what should the next wave focus on",
    "what's the right call here",
    "I want a second opinion",
    "what would you do differently",
    "is there a simpler way",
    "explain this paper to me",
    "what does the literature say about X",
    "convince me this is the right move",
    "play devil's advocate",
    "stress test this idea",
    "what assumptions am I making",
  ],
}

/** All seed strings flattened with their owning route for one-pass embedding. */
export interface Tier0SeedEntry {
  route: Tier0Route
  text: string
}

export const TIER0_SEEDS_FLAT: readonly Tier0SeedEntry[] = (
  Object.entries(TIER0_SEEDS) as [Tier0Route, readonly string[]][]
).flatMap(([route, texts]) => texts.map((text) => ({ route, text })))
